import 'person.dart';

class PersonRepository {
  List<Person>? persons;

  PersonRepository() {
    persons = [
      Person(
          firstname: 'Guido',
          lastname: 'Hinrichs',
          position: 'Developer',
          location: 'Bad Bevensen',
          phone: '0163 5749349'),
      Person(
          firstname: 'Lukas',
          lastname: 'Schmidt',
          position: 'Softwareentwickler',
          location: 'Hamburg',
          phone: '0163 5749349'),
      Person(
          firstname: 'Julia',
          lastname: 'Fischer',
          position: 'Grafikdesignerin',
          location: 'München',
          phone: '0163 5749349'),
      Person(
          firstname: 'Max',
          lastname: 'Klein',
          position: 'Projektmanager',
          location: 'Frankfurt',
          phone: '0163 5749349'),
      Person(
          firstname: 'Lisa',
          lastname: 'Schneider',
          position: 'Sales Managerin',
          location: 'Köln',
          phone: '0163 5749349'),
      Person(
          firstname: 'David',
          lastname: 'Weber',
          position: 'IT-Berater',
          location: 'Düsseldorf',
          phone: '0163 5749349'),
      Person(
          firstname: 'Sophie',
          lastname: 'Hoffmann',
          position: 'HR-Managerin',
          location: 'Stuttgart',
          phone: '0163 5749349'),
      Person(
          firstname: 'Jonas',
          lastname: 'Bauer',
          position: 'Systemadministrator',
          location: 'Leipzig',
          phone: '0163 5749349'),
      Person(
          firstname: 'Mia',
          lastname: 'Zimmermann',
          position: 'Produktdesignerin',
          location: 'Nürnberg',
          phone: '0163 5749349'),
      Person(
          firstname: 'Paul',
          lastname: 'Schulz',
          position: 'Account Manager',
          location: 'Dortmund',
          phone: '0163 5749349'),
      Person(
          firstname: 'Emma',
          lastname: 'Braun',
          position: 'Marketing Spezialistin',
          location: 'Essen',
          phone: '0163 5749349'),
      Person(
          firstname: 'Jan',
          lastname: 'Richter',
          position: 'UX/UI Designer',
          location: 'Bremen',
          phone: '0163 5749349'),
      Person(
          firstname: 'Lea',
          lastname: 'Koch',
          position: 'Forschungsleiterin',
          location: 'Hannover',
          phone: '0163 5749349'),
      Person(
          firstname: 'Simon',
          lastname: 'Jäger',
          position: 'Business Analyst',
          location: 'Dresden',
          phone: '0163 5749349'),
      Person(
          firstname: 'Clara',
          lastname: 'Wagner',
          position: 'Eventmanagerin',
          location: 'Mannheim',
          phone: '0163 5749349'),
      Person(
          firstname: 'Nico',
          lastname: 'Walter',
          position: 'Webentwickler',
          location: 'Karlsruhe',
          phone: '0163 5749349'),
      Person(
          firstname: 'Hannah',
          lastname: 'Schwarz',
          position: 'Content Managerin',
          location: 'Aachen',
          phone: '0163 5749349'),
      Person(
          firstname: 'Tom',
          lastname: 'Lang',
          position: 'SEO-Spezialist',
          location: 'Gießen',
          phone: '0163 5749349'),
      Person(
          firstname: 'Laura',
          lastname: 'Friedrich',
          position: 'Produktmanagerin',
          location: 'Bonn',
          phone: '0163 5749349'),
      Person(
          firstname: 'Markus',
          lastname: 'Schuster',
          position: 'Vertriebsleiter',
          location: 'Paderborn',
          phone: '0163 5749349'),
      Person(
          firstname: 'Nina',
          lastname: 'Mayer',
          position: 'Kommunikationsmanagerin',
          location: 'Würzburg',
          phone: '0163 5749349'),
      Person(
          firstname: 'Felix',
          lastname: 'Becker',
          position: 'Qualitätsmanager',
          location: 'Saarbrücken',
          phone: '0163 5749349'),
      Person(
          firstname: 'Zoe',
          lastname: 'Hahn',
          position: 'IT-Support-Spezialistin',
          location: 'Trier',
          phone: '0163 5749349'),
      Person(
          firstname: 'Jens',
          lastname: 'Kramer',
          position: 'Datenanalyst',
          location: 'Heidelberg',
          phone: '0163 5749349'),
      Person(
          firstname: 'Paula',
          lastname: 'Krause',
          position: 'Einkaufsleiterin',
          location: 'Kaiserslautern',
          phone: '0163 5749349'),
      Person(
          firstname: 'Daniel',
          lastname: 'Wendt',
          position: 'Projektleiter',
          location: 'Rostock',
          phone: '0163 5749349'),
      Person(
          firstname: 'Katrin',
          lastname: 'Nielsen',
          position: 'PR-Managerin',
          location: 'Lübeck',
          phone: '0163 5749349'),
      Person(
          firstname: 'Lena',
          lastname: 'Hertwig',
          position: 'Produktentwicklerin',
          location: 'Flensburg',
          phone: '0163 5749349'),
      Person(
          firstname: 'Christian',
          lastname: 'Schmid',
          position: 'Technischer Support',
          location: 'Göttingen',
          phone: '0163 5749349'),
      Person(
          firstname: 'Maren',
          lastname: 'Hesse',
          position: 'Marktforscherin',
          location: 'Osnabrück',
          phone: '0163 5749349'),
      Person(
          firstname: 'Jakob',
          lastname: 'Schröder',
          position: 'Compliance Officer',
          location: 'Oldenburg',
          phone: '0163 5749349'),
      Person(
          firstname: 'Nadine',
          lastname: 'Pohl',
          position: 'Prozessmanagerin',
          location: 'Erfurt',
          phone: '0163 5749349'),
      Person(
          firstname: 'Oliver',
          lastname: 'Keller',
          position: 'IT-Projektleiter',
          location: 'Cottbus',
          phone: '0163 5749349'),
      Person(
          firstname: 'Franziska',
          lastname: 'Mayer',
          position: 'Online-Marketing-Managerin',
          location: 'Jena',
          phone: '0163 5749349'),
      Person(
          firstname: 'Tobias',
          lastname: 'Hansen',
          position: 'Verkaufsleiter',
          location: 'Magdeburg',
          phone: '0163 5749349'),
      Person(
          firstname: 'Sarah',
          lastname: 'Neumann',
          position: 'Finanzanalystin',
          location: 'Bielefeld',
          phone: '0163 5749349'),
      Person(
          firstname: 'Philipp',
          lastname: 'Seidel',
          position: 'Systems Engineer',
          location: 'Hof',
          phone: '0163 5749349'),
      Person(
          firstname: 'Lilli',
          lastname: 'Krause',
          position: 'Customer Success Managerin',
          location: 'Zwickau',
          phone: '0163 5749349'),
      Person(
          firstname: 'Rico',
          lastname: 'Peters',
          position: 'Technischer Projektmanager',
          location: 'Gera',
          phone: '0163 5749349'),
      Person(
          firstname: 'Marlene',
          lastname: 'Berger',
          position: 'Account Director',
          location: 'Augsburg',
          phone: '0163 5749349'),
      Person(
          firstname: 'Jannik',
          lastname: 'Dorn',
          position: 'Buchhalter',
          location: 'Koblenz',
          phone: '0163 5749349'),
      Person(
          firstname: 'Kerstin',
          lastname: 'Falk',
          position: 'E-Commerce-Managerin',
          location: 'Marl',
          phone: '0163 5749349'),
      Person(
          firstname: 'Stefan',
          lastname: 'Vogel',
          position: 'Supply Chain Manager',
          location: 'Bamberg',
          phone: '0163 5749349'),
      Person(
          firstname: 'Eva',
          lastname: 'Lutz',
          position: 'Betriebswirtin',
          location: 'Tübingen',
          phone: '0163 5749349'),
      Person(
          firstname: 'Gunnar',
          lastname: 'Götz',
          position: 'Fachinformatiker',
          location: 'Reutlingen',
          phone: '0163 5749349'),
      Person(
          firstname: 'Hannah',
          lastname: 'Lorenz',
          position: 'User Experience Designer',
          location: 'Lörrach',
          phone: '0163 5749349'),
      Person(
          firstname: 'Leon',
          lastname: 'Dietrich',
          position: 'Business Development Manager',
          location: 'Landshut',
          phone: '0163 5749349'),
      Person(
          firstname: 'Sophia',
          lastname: 'Gerlach',
          position: 'Energieberaterin',
          location: 'Rosenheim',
          phone: '0163 5749349'),
      Person(
          firstname: 'Andrea',
          lastname: 'Friedrich',
          position: 'IT-Administrator',
          location: 'Weimar',
          phone: '0163 5749349'),
      Person(
          firstname: 'Johanna',
          lastname: 'Ritter',
          position: 'Data Scientist',
          location: 'Hagen',
          phone: '0163 5749349'),
      Person(
          firstname: 'Lars',
          lastname: 'Häuser',
          position: 'Operations Manager',
          location: 'Kempten',
          phone: '0163 5749349'),
      Person(
          firstname: 'Claudia',
          lastname: 'Meyer',
          position: 'Vertragsmanagerin',
          location: 'Pforzheim',
          phone: '0163 5749349'),
      Person(
          firstname: 'Oliver',
          lastname: 'Behrens',
          position: 'Web Analyst',
          location: 'Gütersloh',
          phone: '0163 5749349'),
    ];
  }
}
